import os

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY", "")
ADMIN_TELEGRAM_ID = int(os.getenv("ADMIN_TELEGRAM_ID", "0"))
RENDER_URL = os.getenv("RENDER_EXTERNAL_URL")
DATABASE_URL = os.getenv("DATABASE_URL")

ENABLE_PAYSTACK = bool(PAYSTACK_SECRET_KEY and PAYSTACK_SECRET_KEY.startswith('sk_'))
TRIAL_DAYS = 7
COMMISSION_RATE = 0.05
